name: Navaneeth

on: 
  push:
     branches:  
         - main
  
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: apple
        run: echo "appl"
        
  
  second:
    runs-on: ubuntu-latest
    needs: first
    steps:
      - name: apple
        run: echo "appl"

   